# Communities and Crime Data Set

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Wczytywanie danych

In [2]:
names = !cat './dataset/communities.names' | awk 'NR>=76 && NR<=203 { print $2 }' # nazwy kolumn
informations = !cat './dataset/communities.names' | awk 'NR>=213 && NR<=340 { $1=""; $2=""; print }' # opisy kolumn
attributes = dict(zip(names, informations)) # słownik - nazwa kolumna oraz opis

In [3]:
input_data = pd.read_csv('dataset/communities.data', header=None, names=names)

In [4]:
len(input_data) # liczba wierszy

1994

In [5]:
input_data.shape # liczba wierszy oraz kolumn

(1994, 128)

## Przeglądanie danych

In [6]:
input_data.tail() # oglądamy wstępnie dane

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
1989,12,?,?,TempleTerracecity,10,0.01,0.40,0.10,0.87,0.12,...,0.01,0.28,0.05,?,?,?,?,0.00,?,0.09
1990,6,?,?,Seasidecity,10,0.05,0.96,0.46,0.28,0.83,...,0.02,0.37,0.20,?,?,?,?,0.00,?,0.45
1991,9,9,80070,Waterburytown,10,0.16,0.37,0.25,0.69,0.04,...,0.08,0.32,0.18,0.08,0.06,0.78,0,0.91,0.28,0.23
1992,25,17,72600,Walthamcity,10,0.08,0.51,0.06,0.87,0.22,...,0.03,0.38,0.33,0.02,0.02,0.79,0,0.22,0.18,0.19
1993,6,?,?,Ontariocity,10,0.20,0.78,0.14,0.46,0.24,...,0.11,0.30,0.05,0.08,0.04,0.73,0.5,1.00,0.13,0.48

In [7]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 128 entries, state to ViolentCrimesPerPop
dtypes: float64(100), int64(2), object(26)
memory usage: 1.9+ MB

In [8]:
input_data.describe() # metoda dostarczająca statystyczne informacje o danych w kolumnach
# input_data.describe().T # transpozycja ww. tabeli

,state,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,...,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,ViolentCrimesPerPop
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,...,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000
mean,28.683551,5.493982,0.057593,0.463395,0.179629,0.753716,0.153681,0.144022,0.424218,0.493867,...,0.215552,0.608892,0.535050,0.626424,0.651530,0.065231,0.232854,0.161685,0.094052,0.237979
std,16.397553,2.873694,0.126906,0.163717,0.253442,0.244039,0.208877,0.232492,0.155196,0.143564,...,0.231134,0.204329,0.181352,0.200521,0.198221,0.109459,0.203092,0.229055,0.240328,0.232985
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12.000000,3.000000,0.010000,0.350000,0.020000,0.630000,0.040000,0.010000,0.340000,0.410000,...,0.060000,0.470000,0.420000,0.520000,0.560000,0.020000,0.100000,0.020000,0.000000,0.070000
50%,34.000000,5.000000,0.020000,0.440000,0.060000,0.850000,0.070000,0.040000,0.400000,0.480000,...,0.130000,0.630000,0.540000,0.670000,0.700000,0.040000,0.170000,0.070000,0.000000,0.150000
75%,42.000000,8.000000,0.050000,0.540000,0.230000,0.940000,0.170000,0.160000,0.470000,0.540000,...,0.280000,0.777500,0.660000,0.770000,0.790000,0.070000,0.280000,0.190000,0.000000,0.330000
max,56.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
input_data['communityname'].value_counts().head(10)

Greenvillecity      5
Auburncity          5
Jacksonvillecity    5
Athenscity          4
Salemcity           4
Lebanoncity         4
Lafayettecity       4
Albanycity          4
Springfieldcity     4
Portlandcity        3
Name: communityname, dtype: int64

## Typy danych w zbiorze

In [10]:
input_data.dtypes.value_counts() # wszystkie typy danych

float64    100
object      26
int64        2
dtype: int64

In [11]:
df = input_data.copy() # skopiowanie danych

In [12]:
all(isinstance(i, str) for i in df['communityname']) # sprawdzenie, czy kolumna communityname zawiera tylko stringi

True

In [13]:
cols_numeric = df.columns.drop('communityname') # wszystkie kolumny z wyjątkiem communityname
df[cols_numeric] = df[cols_numeric].apply(pd.to_numeric, errors='coerce') # konwersja wartości na liczby

In [14]:
df.dtypes.value_counts() # wszystkie typy danych

float64    125
int64        2
object       1
dtype: int64

## Zmienne jakościowe

- *state*: identyfikator stanu w USA
- *county*: identyfikator hrabstwa w USA (zawiera braki)
- *community*: identyfikator społeczności  (zawiera braki)
- *communityname*: nazwa społećznosci
- *fold*: liczba krotności w celu walidacji testów

In [15]:
# kolumny zawierające zmienne jakościowe (kategoryczne)
cols_not_predictive = !cat 'dataset/communities.names' | sed '213,340!d' | grep 'not predictive\|not counted as predictive' | awk '{print substr($2, 1, length($2)-1)}'

In [16]:
cols_not_predictive

['state', 'county', 'community', 'communityname', 'fold']

In [17]:
df = df.drop(columns=cols_not_predictive, axis=1)

In [18]:
df.describe()

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,...,1994.000000,1994.000000,1994.000000,319.000000,319.000000,319.000000,319.000000,1994.000000,319.000000,1994.000000
mean,0.057593,0.463395,0.179629,0.753716,0.153681,0.144022,0.424218,0.493867,0.336264,0.423164,...,0.065231,0.232854,0.161685,0.163103,0.076708,0.698589,0.440439,0.094052,0.195078,0.237979
std,0.126906,0.163717,0.253442,0.244039,0.208877,0.232492,0.155196,0.143564,0.166505,0.179185,...,0.109459,0.203092,0.229055,0.214778,0.140207,0.213944,0.405808,0.240328,0.164718,0.232985
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.010000,0.350000,0.020000,0.630000,0.040000,0.010000,0.340000,0.410000,0.250000,0.300000,...,0.020000,0.100000,0.020000,0.040000,0.020000,0.620000,0.000000,0.000000,0.110000,0.070000
50%,0.020000,0.440000,0.060000,0.850000,0.070000,0.040000,0.400000,0.480000,0.290000,0.420000,...,0.040000,0.170000,0.070000,0.080000,0.030000,0.750000,0.500000,0.000000,0.150000,0.150000
75%,0.050000,0.540000,0.230000,0.940000,0.170000,0.160000,0.470000,0.540000,0.360000,0.530000,...,0.070000,0.280000,0.190000,0.195000,0.060000,0.840000,1.000000,0.000000,0.220000,0.330000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Sprawdzanie danych pod kątem wartości pustych

In [19]:
cols_NaN = df.columns[df.isna().any()].tolist() # kolumny zawierające nieznane wartości

In [20]:
len(cols_NaN) # liczba kolumn zawierających brakujące wartości

23

In [21]:
# Look at the features with missing values

df[cols_NaN].describe().T # sprawdzenie kolumn z brakującymi wartościami

                       count      mean       std  min   25%   50%    75%  max
OtherPerCap           1993.0  0.284742  0.191008  0.0  0.17  0.25  0.360  1.0
LemasSwornFT           319.0  0.069655  0.138238  0.0  0.01  0.02  0.060  1.0
LemasSwFTPerPop        319.0  0.217461  0.159928  0.0  0.13  0.18  0.250  1.0
LemasSwFTFieldOps      319.0  0.924734  0.132249  0.0  0.93  0.97  0.980  1.0
LemasSwFTFieldPerPop   319.0  0.246332  0.155045  0.0  0.16  0.21  0.290  1.0
LemasTotalReq          319.0  0.097994  0.161927  0.0  0.02  0.04  0.085  1.0
LemasTotReqPerPop      319.0  0.215204  0.164622  0.0  0.12  0.17  0.250  1.0
PolicReqPerOffic       319.0  0.343636  0.197181  0.0  0.22  0.29  0.435  1.0
PolicPerPop            319.0  0.217492  0.159941  0.0  0.13  0.18  0.250  1.0
RacialMatchCommPol     319.0  0.689404  0.226811  0.0  0.56  0.74  0.860  1.0
PctPolicWhite          319.0  0.726959  0.221409  0.0  0.62  0.78  0.890  1.0
PctPolicBlack          319.0  0.220470  0.236271  0.0  0.05  0.12  0.340  1.0
PctPolicHisp           319.0  0.134859  0.196188  0.0  0.01  0.06  0.170  1.0
PctPolicAsian          319.0  0.114859  0.227348  0.0  0.00  0.00  0.120  1.0
PctPolicMinor          319.0  0.259185  0.225655  0.0  0.09  0.20  0.350  1.0
OfficAssgnDrugUnits    319.0  0.075549  0.120153  0.0  0.02  0.04  0.080  1.0
NumKindsDrugsSeiz      319.0  0.556050  0.203178  0.0  0.43  0.57  0.675  1.0
PolicAveOTWorked       319.0  0.305987  0.226884  0.0  0.14  0.26  0.395  1.0
PolicCars              319.0  0.163103  0.214778  0.0  0.04  0.08  0.195  1.0
PolicOperBudg          319.0  0.076708  0.140207  0.0  0.02  0.03  0.060  1.0
LemasPctPolicOnPatr    319.0  0.698589  0.213944  0.0  0.62  0.75  0.840  1.0
LemasGangUnitDeploy    319.0  0.440439  0.405808  0.0  0.00  0.50  1.000  1.0
PolicBudgPerPop        319.0  0.195078  0.164718  0.0  0.11  0.15  0.220  1.0

In [22]:
[x + ' -' + attributes[x] for x in cols_NaN] # opis kolumn z nieznanymi wartościami

["OtherPerCap -  per capita income for people with 'other' heritage (numeric - decimal)",
 'LemasSwornFT -  number of sworn full time police officers (numeric - decimal)',
 'LemasSwFTPerPop -  sworn full time police officers per 100K population (numeric - decimal)',
 'LemasSwFTFieldOps -  number of sworn full time police officers in field operations (on the street as opposed to administrative etc) (numeric - decimal)',
 'LemasSwFTFieldPerPop -  sworn full time police officers in field operations (on the street as opposed to administrative etc) per 100K population (numeric - decimal)',
 'LemasTotalReq -  total requests for police (numeric - decimal)',
 'LemasTotReqPerPop -  total requests for police per 100K popuation (numeric - decimal)',
 'PolicReqPerOffic -  total requests for police per police officer (numeric - decimal)',
 'PolicPerPop -  police officers per 100K population (numeric - decimal)',
 'RacialMatchCommPol -  a measure of the racial match between the community and the police force. High values indicate proportions in community and police force are similar (numeric - decimal)',
 'PctPolicWhite -  percent of police that are caucasian (numeric - decimal)',
 'PctPolicBlack -  percent of police that are african american (numeric - decimal)',
 'PctPolicHisp -  percent of police that are hispanic (numeric - decimal)',
 'PctPolicAsian -  percent of police that are asian (numeric - decimal)',
 'PctPolicMinor -  percent of police that are minority of any kind (numeric - decimal)',
 'OfficAssgnDrugUnits -  number of officers assigned to special drug units (numeric - decimal)',
 'NumKindsDrugsSeiz -  number of different kinds of drugs seized (numeric - decimal)',
 'PolicAveOTWorked -  police average overtime worked (numeric - decimal)',
 'PolicCars -  number of police cars (numeric - decimal)',
 'PolicOperBudg -  police operating budget (numeric - decimal)',
 'LemasPctPolicOnPatr -  percent of sworn full time police officers on patrol (numeric - decimal)',
 'LemasGangUnitDeploy -  gang unit deployed (numeric - decimal - but really ordinal - 0 means NO, 1 means YES, 0.5 means Part Time)',
 'PolicBudgPerPop -  police operating budget per population (numeric - decimal)']

In [23]:
sum([True for idx,row in df.iterrows() if any(row.isnull())]) # zliczanie wierszy, które mają brakujące wartości

1675

In [24]:
sum(df.isnull().values.ravel()) # liczenie komórek brakujących wartości

36851

In [25]:
len(df.dropna()) # liczba wierszy niezawierajacych nieznane wartości

319

In [26]:
pd.isnull(df[cols_NaN]).sum() # liczba wierszy zawierające brakujace wartosci

OtherPerCap                1
LemasSwornFT            1675
LemasSwFTPerPop         1675
LemasSwFTFieldOps       1675
LemasSwFTFieldPerPop    1675
LemasTotalReq           1675
LemasTotReqPerPop       1675
PolicReqPerOffic        1675
PolicPerPop             1675
RacialMatchCommPol      1675
PctPolicWhite           1675
PctPolicBlack           1675
PctPolicHisp            1675
PctPolicAsian           1675
PctPolicMinor           1675
OfficAssgnDrugUnits     1675
NumKindsDrugsSeiz       1675
PolicAveOTWorked        1675
PolicCars               1675
PolicOperBudg           1675
LemasPctPolicOnPatr     1675
LemasGangUnitDeploy     1675
PolicBudgPerPop         1675
dtype: int64

Kolumna **OtherPerCap** zawiera tylko jedną brakującą wartość.

In [27]:
# uzupełnienie braków w OtherPerCap średnią korzystając z Imputer z sklearn.preprocessing
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(df[['OtherPerCap']])
df[['OtherPerCap']] = imputer.transform(df[['OtherPerCap']])

Pozostałe kolumny mają za dużo brakujących wartości, zatem je usuniemy.

In [28]:
df = df.dropna(axis=1) # usunięcie kolumn zawierających nieznane wartości

In [29]:
df.shape

(1994, 101)

In [30]:
', '.join(sorted(list(df.columns), key=lambda s: s.lower())) # nazwy kolumn

'agePct12t21, agePct12t29, agePct16t24, agePct65up, AsianPerCap, blackPerCap, FemalePctDiv, HispPerCap, householdsize, HousVacant, indianPerCap, LandArea, LemasPctOfficDrugUn, MalePctDivorce, MalePctNevMarr, medFamInc, medIncome, MedNumBR, MedOwnCostPctInc, MedOwnCostPctIncNoMtg, MedRent, MedRentPctHousInc, MedYrHousBuilt, numbUrban, NumIlleg, NumImmig, NumInShelters, NumStreet, NumUnderPov, OtherPerCap, OwnOccHiQuart, OwnOccLowQuart, OwnOccMedVal, PctBornSameState, PctBSorMore, PctEmplManu, PctEmploy, PctEmplProfServ, PctFam2Par, PctForeignBorn, PctHousLess3BR, PctHousNoPhone, PctHousOccup, PctHousOwnOcc, PctIlleg, PctImmigRec10, PctImmigRec5, PctImmigRec8, PctImmigRecent, PctKids2Par, PctLargHouseFam, PctLargHouseOccup, PctLess9thGrade, PctNotHSGrad, PctNotSpeakEnglWell, PctOccupManu, PctOccupMgmtProf, PctPersDenseHous, PctPersOwnOccup, PctPopUnderPov, PctRecentImmig, PctRecImmig10, PctRecImmig5, PctRecImmig8, PctSameCity85, PctSameHouse85, PctSameState85, PctSpeakEnglOnly, PctTeen2Par, PctUnemployed, pctUrban, PctUsePubTrans, PctVacantBoarded, PctVacMore6Mos, pctWFarmSelf, pctWInvInc, PctWOFullPlumb, PctWorkMom, PctWorkMomYoungKids, pctWPubAsst, pctWRetire, pctWSocSec, pctWWage, PctYoungKids2Par, perCapInc, PersPerFam, PersPerOccupHous, PersPerOwnOccHous, PersPerRentOccHous, PopDens, population, racePctAsian, racepctblack, racePctHisp, racePctWhite, RentHighQ, RentLowQ, RentMedian, TotalPctDiv, ViolentCrimesPerPop, whitePerCap'

In [31]:
df.to_pickle('files/dataframe.pkl') # zapis do pliku dataframe.pkl